<?php

namespace ContainerIf30xD2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_06s6YSEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.06s6YSE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.06s6YSE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'productStock' => ['privates', '.errored..service_locator.06s6YSE.App\\Entity\\ProductStock', NULL, 'Cannot autowire service ".service_locator.06s6YSE": it needs an instance of "App\\Entity\\ProductStock" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'productStock' => 'App\\Entity\\ProductStock',
        ]);
    }
}
