<?php

namespace ContainerIf30xD2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoriesTree2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ozMJT7b.App\Entity\CategoriesTree' shared service.
     *
     * @return \App\Entity\CategoriesTree
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ozMJT7b": it needs an instance of "App\\Entity\\CategoriesTree" but this type has been excluded in "config/services.yaml".');
    }
}
