<?php

namespace ContainerIf30xD2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductStock3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Lal9dGx.App\Entity\ProductStock' shared service.
     *
     * @return \App\Entity\ProductStock
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Lal9dGx": it needs an instance of "App\\Entity\\ProductStock" but this type has been excluded in "config/services.yaml".');
    }
}
