<?php

namespace ContainerIf30xD2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_LiveComponent_MetadataFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux.live_component.metadata_factory' shared service.
     *
     * @return \Symfony\UX\LiveComponent\Metadata\LiveComponentMetadataFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-live-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Metadata'.\DIRECTORY_SEPARATOR.'LiveComponentMetadataFactory.php';

        $a = ($container->privates['ux.twig_component.component_factory'] ?? $container->load('getUx_TwigComponent_ComponentFactoryService'));

        if (isset($container->privates['ux.live_component.metadata_factory'])) {
            return $container->privates['ux.live_component.metadata_factory'];
        }

        return $container->privates['ux.live_component.metadata_factory'] = new \Symfony\UX\LiveComponent\Metadata\LiveComponentMetadataFactory($a, ($container->privates['property_info'] ?? self::getPropertyInfoService($container)));
    }
}
