<?php

namespace Container2m0H977;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JXXzmCkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JXXzmCk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JXXzmCk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'productStock' => ['privates', '.errored..service_locator.JXXzmCk.App\\Entity\\ProductStock', NULL, 'Cannot autowire service ".service_locator.JXXzmCk": it needs an instance of "App\\Entity\\ProductStock" but this type has been excluded in "config/services.yaml".'],
        ], [
            'productStock' => 'App\\Entity\\ProductStock',
        ]);
    }
}
