<?php

namespace Container2m0H977;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FIMPIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._FIMP_i' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._FIMP_i'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'productImage' => ['privates', '.errored..service_locator._FIMP_i.App\\Entity\\ProductImages', NULL, 'Cannot autowire service ".service_locator._FIMP_i": it needs an instance of "App\\Entity\\ProductImages" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'productImage' => 'App\\Entity\\ProductImages',
        ]);
    }
}
