<?php

namespace Container2m0H977;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductSearchComponentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Twig\Components\ProductSearchComponent' autowired service.
     *
     * @return \App\Twig\Components\ProductSearchComponent
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-live-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'DefaultActionTrait.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Twig'.\DIRECTORY_SEPARATOR.'Components'.\DIRECTORY_SEPARATOR.'ProductSearchComponent.php';

        $container->factories['App\\Twig\\Components\\ProductSearchComponent'] = function ($container) {
            return new \App\Twig\Components\ProductSearchComponent(($container->privates['App\\Repository\\ProductRepository'] ?? $container->load('getProductRepositoryService')));
        };

        return $container->factories['App\\Twig\\Components\\ProductSearchComponent']($container);
    }
}
