<?php

namespace Container2m0H977;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductImagesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MpQVtVm.App\Entity\ProductImages' shared service.
     *
     * @return \App\Entity\ProductImages
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.MpQVtVm": it needs an instance of "App\\Entity\\ProductImages" but this type has been excluded in "config/services.yaml".');
    }
}
