<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIf30xD2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIf30xD2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIf30xD2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIf30xD2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIf30xD2\App_KernelDevDebugContainer([
    'container.build_hash' => 'If30xD2',
    'container.build_id' => '34477ee5',
    'container.build_time' => 1711898463,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIf30xD2');
